### ISSUE TITLE
Create mod Update?

### ISSUE THREAD

**Issue by DOLK2000** [ZoesDev/endofmine1.18#6]
when will the modpack be updated with the new create mod futhers.
just wantend to ask because, i just cant wait to test things out with it on this pack ^-^;

With the greetings from,
DOLK2000

**Comment by ZoesDev** [comment]
Hi DOLK200, I Have actually been working on it over the weekend and hoping to get an update out today or tomorrow. I will update this comment when it is uploaded and waiting for approval from CurseForge.

**Comment by ZoesDev** [comment]
Modpack is updated and just waiting for approval and server pack to upload. Closing issue.
