### ISSUE TITLE
bug or glitch?

### ISSUE THREAD

**Issue by DOLK2000** [ZoesDev/endofmine1.18#7]
Hello,

So i saw that the packs new update was released and i directly went to download the update but for some reason it didnt wantend to update and kept on cancelen i trying removing the whole pack and installing it again but yet again it didnt let me and canceled i dont understand why i should have enough space on my pc and i also increased minecraft GB use allowed from 10k MB to 17k MB from what it noticed it everytime stoped working when Patching 1 of 6 came in screen and right after that cancel

With Friendly greetings from,
DOLK2000-

**Comment by ZoesDev** [comment]
can you post the latest log to gist.github.com and post a link? you may want to do a once over and check if you need to sanatize the data in the log as sometimes it includes full paths to the install which can your full name sometimes if you use that for your login name.

as for memory, I only have 8gb assigned to the pack and it is working fine.

if you want. backup worlds in the save folder and then delete the profile and reinstall with curseforge. there are issues sometimes with curseforge not loading things correctly. 

can you also include cpu and ram that you have?


I currently have 10 people on the server I am using for the modpack without anyone else having issues.

**Comment by DOLK2000** [comment]
My pc has:
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
Apacer SM210 M280 SATA 512GB
TOSHIBA DT01ACA100
NVIDiA GeForce GTX 1060 3GB

i am only not sure where to find the logs in question seeing as i dont see and recent logs because when i try updating the pack or installing it i can find a log in the twitch>Minecraft>Install>Logs and the log that is in there only contains:
[21:48:16] [main/INFO]: Building optimized [datafixer]
i will add some videos and screen shot of how i currently see it all
(nevermind i am not allowed to send screenshots or video's)

or there gotta be a other way i can share it but the best i can explane in words is this

**Comment by ZoesDev** [comment]
oh. ok. sorry was miss understanding the spot it was getting sutck on. yeah this is most likely a curseforge bug. only way to fix it is go to minecraft folder and save the world files. then delete  the instance in curseforge and then redownload the whole modpack. I have seen this happen a bunch of times with other modpacks. after the pack is reinstalled you can copy the save folder back into the modpack and have your world again, you may want to also save the journeymap folder as it has the map data in it for the mini map and waypoints.

**Comment by DOLK2000** [comment]
[20220712_212105.webm](https://user-images.githubusercontent.com/109076403/178781500-15a59081-12a1-495c-a894-0d7e98901484.webm)

**Comment by DOLK2000** [comment]
![20220712_215217](https://user-images.githubusercontent.com/109076403/178781825-bf3e829e-822d-41d1-93b6-80cc732a3564.jpg)
![20220712_215559](https://user-images.githubusercontent.com/109076403/178781853-1affc5eb-8b84-4198-b31a-e9a51b43c912.jpg)

**Comment by DOLK2000** [comment]
[20220712_214953_Trim_Trim.webm.webm](https://user-images.githubusercontent.com/109076403/178784479-e4553b8f-9e26-40bc-b6f2-a38081399c3c.webm)

**Comment by DOLK2000** [comment]
this is what happens when i try to update or to instal the 1.2.4 version because i can only seem to do 1.2.3 and below but the new one i cant

**Comment by ZoesDev** [comment]
Ok messing around on and off today with this. I am finally able to replicate it and even cant install fresh. it looks like it is a weird issue with curseforge not able to install forge for some reason. can you try downloading the zip from curseforge here and importing it as a custom pack install? https://www.curseforge.com/minecraft/modpacks/end-of-mine-server-pack/files/3870711 click download instead of install. And let me know if that works. tryign to see if maybe its a forge issue with 40.1.60 or curseforge being stupid. if it doesnt work have you rebooted your pc? made sure permissions on the folder for the instance are read/write and not read only which happens sometimes on windows.

**Comment by ZoesDev** [comment]
if what I posted doesnt help. I think its an issue with curseforge and as such it maybe easier/better to go to their support on discord for figuring out whats going on. https://discord.com/invite/curseforge closing this issue as it doesnt seem to be an issue with the modpack directly and more todo with the way curseforge it working.
